ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Context and scope - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.

.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****
endif::arc42help[]

=== Business Context

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****
endif::arc42help[]

[plantuml,"C4 Diagram - Business context", png, align="center", title="Overall view of the business context"]
----
include::./diagrams/S3_C4_Business_Context_Diagram.puml[]
----
The business model diagram represents how the player interacts with the system of the WiChat application. The core API will communicate with the external WikiData API using the HTTPS protocol and SPARQL queries to retrieve the information, using independent modules that generate a microservice architecture to decouple the system. The data retrieved by the API will be used to generate the questions that the player must answer. In this case, an image will be retrieved, and the player must select the option that best fits what is shown in the picture. The player can also ask for help, interacting with an LLM Chat, provided by another external API. The LLM will use the information from the WikiData API without direct interaction to provide clues about the image (the corresponding modules are in charge of gathering the information from WikiData API and passing it to the LLM API).

A simple example of the functioning of the system is the following: the player logs in and starts a game. The system retrieves data from the WikiData API and generates the image and the possible answers (for example, an image of the Eiffel Tower, and four cities of Europe, like Madrid, Rome, London and Paris). The player may ask for help to the LLM Chat if he/she is not sure about the answer, and the AI will use the information from the WikiData API to provide clues about the image. The player can then select the correct answer, and the system will inform if it is correct or not. After the game is finished the user will see the game results and can access his statistics and the leaderboards.

=== Technical Context

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****
endif::arc42help[]

[plantuml, "C4 Diagram - Technical context diagram", png, align="center", title="Overall view of the technical context"]
----
include::./diagrams/S3_C4_Technical_Context_Diagram.puml[]
----
The system will be deployed over a virtual machine in a single Azure server (using **Docker**) containing all the functionalities separated in different modules:

* **Wichat Application Proxy:**
When interacting with the server, a Nginx proxy gateway will be tasked with redirecting incoming requests to the Wichat application client, which will also be deployed on the Azure web server.

* **Wichat Application Client:**
This client will be served to the user and communicates with the API through HTTPS calls and exchanges information through JSON objects. The client (Front-End of the application) will be developed in React (+ JavaScript).

* **Wichat REST API:**
The Wichat REST API will be run as a .jar file on the server and connect to a database running on a MongoDB docker container.

* **Question generator:**
The Question Generator will use the external WikiData REST API to retrieve the information to generate the images and questions of the quiz. It will connect to the WikiData REST API through HTTPS calls, passing a Mongo Query Language (MQL) query to retrieve the data that will later be used as the questions of the game. The module is implemented using Node.js and uses Axios for making HTTP requests.

* **Wichat Application Database:**
The questions and answers generated by the Question Generator module will be stored in a MongoDB database. It is supposed to be a unique database for the entire system, but containing several different collections for a series of purposes (one for user session data, other for quiz questions, other for statistics and game data...). The connection layer will use Mongoose.
