ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
endif::arc42help[]

=== Technologies used
- React is used for the front-end of the application. This framework, at the time of the decision, was highly popular, and its demmand in the market, as well as the familiarity of part of the front-end team, influenced the decision.
- MongoDB is used, due to the base project already supporting it and the interest of the team to learn how to use it.
- NodeJs supports the backend, at the time of writing this, due to the base project using it by default, and its relatively low complexity to begin compared to springboot.
- Git is used as a version control, implemented in github, due to the common use of this web page and the toolset it provides. Focusing on git, this technology is used due to the familiarity all team members share with it.
- Swagger is a tool used in the API's design and documentation. It was used due to a constraint of the employers.
- Commit messages are written following the convention described https://www.conventionalcommits.org/en/v1.0.0/[here] to ensure meaningful commit names.
- Branch names follow a simplification of the strategy described https://medium.com/@abhay.pixolo/naming-conventions-for-git-branches-a-cheatsheet-8549feca2534[here] and it is used to ease the documentation, identification and meaninful naming of development branches. 
- Github Flow is followed as a branch strategy, as the size of the project is expected to be medium and we deemed a hotfix branch and a release branch excessive overhead. 
- Use of semantic versioning (https://semver.org/) for specifying versions meaningfully.

=== Workflow of the team

The team makes use of an agile framework called kanban to ease the software development process. Therefore, tasks are "hung up" on a kanban board on Github to keep track of which tasks are pending or in progress. The modelled tasks are Github Issues, and are expected to follow the INVEST acronym commonly used on agile frameworks. (link:https://en.wikipedia.org/wiki/INVEST_(mnemonic)[mnemonic explanation])

The team's schedule, apart from a mandatory meeting per week, is up to the team members and the needs of the project. The collaborators do not have a fixed timetable but rather are expected to bear the responsability of their work. 

=== Team organization and structure

The team, as discussed on the first and second meetings, decided to divide the workload based on frontend and backend, virtually splitting the team in two subteams, each specialized in one of those. However, the teammembers are not expected to act as experts or be irreplaceable, so the subteam composition is to remain flexible. Here is the expected division of the work:

[options="header"]
|=== 
|Contributor                | Role
|Miguel Álvarez Hernández   | Backend
|Marcos Losada García       | Backend
|María Rodríguez Gómara     | Backend
|Javier Carrasco Arango     | Frontend
|Vicente Megido García      | Frontend
|===

To avoid losing a team member and the collapse of the project this could entail, architectural and design decisions are documented on this documentation, as well as in the wiki. Furthermore, the team is actively involved in all processes of the system, directly coding or indirectly helping each other via extraofficial comunication on whatsapp.

=== Third parties and the responsabilities delegated to them 

- The team delegates the responsabilty of the version control's remote server to Github, as it is expected to be up and working most of the time.
- Extraofficial communications are delegated to Whatsapp, as it is the easiest contact method between the team members and all the team personally knowing each other. Otherwise, tools like matrix messaging would be preferred.
- University of Oviedo provides the installations and the technical assistance for the team's mandatory meeting, as well as the contact mail domain.
