ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

In this section, some sequence diagrams that represent the runtime view of the system are presented. The sequence diagrams are used to show the interactions between the building blocks of the system in different scenarios, generating a workflow that helps to imagine how the ideal interaction of a regular user with the application should be.

=== Registration and Login

The following sequence diagrams represent the process of registration and login in the system. The diagrams show the interactions between the user, the main API of the application, and the database, representing the steps that are followed in each scenario.

[plantuml, "Sequential diagram of the process of registration", png, align="center", title="Registration Sequence Diagram"]
----
include::./diagrams/Sequence_diagram_Registration.puml[]
----

[plantuml, "Sequential diagram representing the Log In process", png, align="center", title="Login Sequence Diagram"]
----
include::./diagrams/Sequence_diagram_Login.puml[]
----

=== Game lifecycle

The following sequence diagram represents the lifecycle of a game in the system. The diagram shows the interactions between the user, the main API of the application, the LLM API that provides the chat to ask for hints, and the database. The different steps that can be followed will be represented.

[plantuml, "Sequential diagram representing the interaction in a game session", png, align="center", title="Game's Lifecycle Sequence Diagram"]
----
include::./diagrams/Sequence_diagram_Game.puml[]
----

=== Question generation process

The following sequence diagram represents the process of generating questions in the system. The diagram shows the interactions between the Question Generator, the WikiData API that provides the answers to the questions, and the database. The information exchange process will be represented.

[plantuml, "Sequential diagram representing the question generation process", png, align="center", title="Question Generation Sequence Diagram"]
----
include::./diagrams/Sequence_diagram_Question_Generation.puml[]
----
