ifndef::imagesdir[:imagesdir: ../images]

[[section-technical-risks]]
== Risks and Technical Debts

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.


.Further Information

See https://docs.arc42.org/section-11/[Risks and Technical Debt] in the arc42 documentation.

****
endif::arc42help[]

=== Risks
==== WikiData API
The API from where the system obtains the data and generates questions from may be unavailable at any point. This has a low chance of happening but nevertheless it's something to consider.

==== The central server
The system's deployment server may experience downtime for an indefinite duration. The risk is low- yet present due to our inexperience in its management. This risk is mitigated by the prospect of automatic deployment using docker.

==== Poor documentation
Even following the clear steps layed out for us, we are inexperienced in the role of a software architect, as well as lack the experience in open source projects of a senior programmer, the project's documentation may be lacking compared. This risk only can be mitigated by either trial and error or external help of some seasoned developer.

==== MongoDb
The use of this database technology is still to be decided on, but the current placeholder has the risk of losing data consistency. Due to the eventual consistency property of some noSql systems, we may encounter situations where data becomes corrupted.

=== Technical debt
Here is listed the known negative impact of decisions taken by the team. This section is expected to increase every time one is identified. 