@startuml C4_Deployment_Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

title Deployment Diagram for the WiChat Application

Deployment_Node(serverNode, "Application Server", "Ubuntu VM (Azure)") {
    Container(client, "Web Client (UI)", 3000)
    Container(gateway, "Gateway Service", 8000)
    Container(users, "Users Service", 8001)
    Container(auth, "User Authentication Service", 8002)
    Container(qg, "Question Generator Service", 8004)
    Container(llm, "LLM Service", 8003)
    Container(game, "Game Service", 8005)
    ContainerDb(db, "MongoDB", 27017)
}

client -> gateway: HTTP/HTTPS
Rel(gateway, auth, "")
Rel(gateway, users, "")
Rel(gateway, qg, "")
Rel(gateway, llm, "")
Rel(gateway, game, "")
BiRel(auth, db, "")
BiRel(users, db, "")
BiRel(game, db, "")
Rel(qg, db, "")

@enduml
