@startuml Domain_Model

entity "User" {
  * username: String
    - required, unique, regex: /^[a-zA-Z0-9_]+$/, 3–30 chars
  * password: String
    - required
  * createdAt: Date = now
}

entity "Score" {
  * userId: String
    - references User._id
  * score: Number = 0
  * gameMode: String ['basicQuiz', 'expertDomain', 'timeAttack', 'endlessMarathon', 'custom']
    - required
  * questionsPassed: Number = 0
  * questionsFailed: Number = 0
  * accuracy: Number = 0
  * meanTimeToAnswer: Number = 0
  * createdAt: Date = now
}

entity "Question" {
  * question: String
    - required
  * answers: [Object]
    - required
  * correctAnswerId: Number
    - required
  * type: String
    - required
  * image: String
    - optional
  * createdAt: Date = now (expires in 30 min)
}

@enduml