@startuml Domain_Model

skinparam componentStyle rectangle

actor UserClient

rectangle "API Gateway" {
  [Gateway API]
}

package "Microservices" {
  [Auth Service] as AuthSvc
  [Question Service] as QuestionSvc
  [Game Service] as GameSvc
  [LLM Service] as LLM
  [User Service] as UserSvc
}

UserClient --> [Gateway API] : Client interacts with the gateway
[Gateway API] --> AuthSvc : /login
[Gateway API] --> QuestionSvc : /generate-questions, /questions/:type/:limit, /question
[Gateway API] --> GameSvc : /saveScore, /scoresByUser, /leaderboard
[Gateway API] --> LLM : /askllm, /aiBuddy
[Gateway API] --> UserSvc : /signup


@enduml
