@startuml C4_Business_Context_Diagram
!include <C4/C4_Container>

top to bottom direction

Person(user, "User")
System_Boundary(quizGame, "WiChat Application") {
    System(wichat, "WiChat Main API", "Main system / interface to provide the quiz game service")
    System(gateway, "WiChat Gateway Module", "Stands as a façade for the rest of the modules", "Internal system")
    Container(llmChat, "LLM AI Chat", "Empathy", "Application service that works as an interface with the LLM API", "Internal system")
    Container(auth, "Authentication Module", "", "Application module to manage the sessions and authentications", "Internal system")
    Container(user, "User Module", "", "Application module to manage the users", "Internal system")
    Container(gameService, "Game Module", "", "Application module that provides the game logic", "Internal system")
    Container(questionGen, "Question Generator", "", "Application module that generates the questions of the game using information from Wikidata", "Internal system")
    SystemDb(mongodb, "MongoDB Database", "Database to store the game questions, possible answers, the user data, rankings and other statistics")    
}
System_Ext(wikidata, "WikiData API", "External resource to provide data for the questions and images")
System_Ext(llm, "LLM API", "External resource to provide hints")


Rel(wichat, gateway, "Uses")
Rel(gateway, llmChat, "Provides")
Rel(gateway, auth, "Provides")
Rel(gateway, user, "Provides")
Rel(gateway, questionGen, "Provides")
Rel(gateway, gameService, "Provides")
Rel(llmChat, llm, "Connects to")
Rel(user, mongodb, "Stores data in")
Rel(auth, mongodb, "Stores data in")
Rel(questionGen, mongodb, "Stores data in")
Rel(gameService, mongodb, "Stores data in")
Rel(questionGen, wikidata, "Collects data from")

@enduml
