@startuml game
title Game's lifecycle Sequence Diagram

actor User #DarkGreen
participant GUI as "GUI" #WhiteSmoke
participant mainAPI as "Main App API" #Aqua
participant gameAPI as "Game API" #SkyBlue
participant LLM as "LLM" #IndianRed
database DB as "Database" #LightGray
participant QG as "Question Generator" #LightYellow

skinparam Style strictuml
skinparam SequenceMessageAlignment center

User -> GUI : Select game mode and start game
activate GUI #WhiteSmoke
GUI -> mainAPI : Request game start
activate mainAPI #Aqua
mainAPI -> gameAPI : Start game
activate gameAPI #SkyBlue
gameAPI -> DB : Request questions
activate DB #LightGray
DB -> QG : Ask for questions
activate QG #LightYellow
QG -> QG : Generate questions
QG --> DB : Return questions
deactivate QG
DB --> gameAPI : Store questions and answers context
deactivate DB
loop #MediumSeaGreen Round
    gameAPI -> gameAPI : Select question
    gameAPI --> mainAPI : Return selected question
    mainAPI --> GUI : Display selected question
    GUI --> User : Show question and options
    opt Request hint from LLM (optional)
        User -> GUI : Select request hint (query)
        GUI -> mainAPI : Request hint
        mainAPI -> LLM : Query LLM chat for hint
        activate LLM #IndianRed
        LLM --> mainAPI : Return hint
        deactivate LLM
        mainAPI --> GUI : Return hint
        GUI --> User : Show hint
    end  
    User -> GUI : Select answer
    GUI -> mainAPI : Send answer
    mainAPI -> gameAPI : Request answer check
    gameAPI -> gameAPI : Check answer
    gameAPI --> mainAPI : Send question result
    mainAPI --> GUI : Display question result
    GUI --> User : Show question result
    gameAPI -> gameAPI : Update game context
    gameAPI --> mainAPI : Return game info updated
    mainAPI --> GUI : Display game info updated
    GUI --> User : Show game info updated
end loop Round
gameAPI -> DB : [After last question] Update ranking
activate DB #LightGray
DB --> gameAPI : Return updated rankings
deactivate DB
gameAPI --> mainAPI : Return results
deactivate gameAPI
mainAPI --> GUI : Display results
deactivate mainAPI
GUI --> User : Show results
deactivate GUI
@enduml
