@startuml register
title Registration Sequence Diagram

actor User #DarkGreen
participant GUI as "GUI" #WhiteSmoke
participant mainAPI as "Main App API" #Aqua
participant authAPI as "Authentication API" #SkyBlue
database DB as "Database" #LightGray

skinparam Style strictuml
skinparam SequenceMessageAlignment center

User -> GUI : Input account details
activate GUI #WhiteSmoke
GUI -> mainAPI : Request account creation
activate mainAPI #Aqua
mainAPI -> authAPI : Request account details validation
activate authAPI #SkyBlue
authAPI -> DB : Check email account is unused
activate DB #LightGray
alt #MediumSeaGreen Email available
    DB --> authAPI : Available and valid credentials
    deactivate DB
    authAPI -> DB : Register user
    activate DB #LightGray
    DB --> authAPI : User registered
    deactivate DB
    authAPI --> mainAPI : Return confirmation
    deactivate authAPI
    mainAPI --> GUI : Return confirmation and register
    deactivate mainAPI
    GUI --> User : Show confirmation message
else Email already in use
    activate DB #LightGray
    activate authAPI #SkyBlue
    activate mainAPI #Aqua
    DB --> authAPI : Email is used
    deactivate DB
    authAPI --> mainAPI : Return error in request
    deactivate authAPI
    mainAPI --> GUI : Show error ("409 Conflict")
    deactivate mainAPI
    GUI --> User : Show error message
    deactivate GUI
end
@enduml
