@startuml question_generation
title Question Generation Sequence Diagram

participant mainAPI as "Main API" #Aqua
participant QG as "Question Generator" #OliveDrab
participant WD as "WikiData" #GreenYellow
database DB as "Database" #LightGray

skinparam Style strictuml
skinparam SequenceMessageAlignment center

loop #darkseagreen Generate question templates
    activate mainAPI #Aqua
    activate QG #OliveDrab
    QG -> WD : Request query template
    activate WD #GreenYellow
    WD --> QG : Return query answers
    deactivate WD
    QG -> QG : Process query answer
    QG -> DB : Store answers
    activate DB #LightGray
    QG -> DB : Store questions
end loop
DB --> QG : Data saved
deactivate DB
QG --> mainAPI : Return question templates
deactivate QG
deactivate mainAPI
@enduml
