@startuml login
title Login Sequence Diagram

actor User #DarkGreen
participant GUI as "GUI" #WhiteSmoke
participant mainAPI as "Main App API" #Aqua
participant authAPI as "Authentication API" #SkyBlue
database DB as "Database" #LightGray

skinparam Style strictuml
skinparam SequenceMessageAlignment center

User -> GUI : Enter credentials
activate GUI #WhiteSmoke
GUI -> mainAPI : Request login
activate mainAPI #Aqua
mainAPI -> authAPI : Request credentials validation
activate authAPI #SkyBlue
authAPI -> DB : Check credentials
activate DB #LightGray
alt #MediumSeaGreen Valid credentials
    DB --> authAPI : Credentials are valid
    deactivate DB
    authAPI -> authAPI : Generate JWT and refresh tokens
    authAPI -> DB : Store session tokens
    activate DB #LightGray
    DB --> authAPI : Tokens saved
    deactivate DB
    authAPI --> mainAPI : Return JWT DTO
    deactivate authAPI
    mainAPI --> GUI : Return JWT DTO
    deactivate mainAPI
    GUI --> User : Show main app
else Invalid credentials
    activate DB #LightGray
    activate authAPI #SkyBlue
    activate mainAPI #Aqua
    DB --> authAPI : Invalid credentials
    deactivate DB
    authAPI --> mainAPI : Return error ("Invalid credentials")
    deactivate authAPI
    mainAPI --> GUI : Return error ("401 Unauthorized")
    deactivate mainAPI
    GUI --> User : Show error message
    deactivate GUI
end
@enduml
